spring:
  application:
    name: projetodb
  datasource:
    url: jdbc:postgresql://localhost:5432/voluntariadoAPI
    username: postgres
    password: 0816
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG